### ISSUE TITLE
is there any document for aslam_optimizer?

### ISSUE THREAD

**Issue by xiaoyaoE** [ethz-asl/aslam_optimizer#212]
Hi, is there any document for using aslam_optimizer?
Thanks!

**Comment by HannesSommer** [comment]
There is an slightly outdated document in https://github.com/ethz-asl/aslam_optimizer/tree/master/aslam_backend_tutorial/tex . 
Additionally there are some examples with comments in https://github.com/ethz-asl/aslam_optimizer/tree/master/aslam_backend_tutorial/ , which should be a little more up to date.  

If you run into issues please feel free to propose updates / changes.

**Comment by HannesSommer** [comment]
You are welcome :).
